// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkEfL_ru7e2kzPpi-dpS4Ee9-T5sFVTeY',
    appId: '1:782550248358:web:198c3c7b67a5044c443d67',
    messagingSenderId: '782550248358',
    projectId: 'newpr-a6131',
    authDomain: 'newpr-a6131.firebaseapp.com',
    storageBucket: 'newpr-a6131.appspot.com',
    measurementId: 'G-C1KBSH31EK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3IgrE65dn2rbSF81hHHZE_OwBYhK79fM',
    appId: '1:782550248358:android:b4ec9a0c1cd993f7443d67',
    messagingSenderId: '782550248358',
    projectId: 'newpr-a6131',
    storageBucket: 'newpr-a6131.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRlPUF_rTorkZTteByKoIBECZEMrDVwTk',
    appId: '1:782550248358:ios:2eb3354766d7907e443d67',
    messagingSenderId: '782550248358',
    projectId: 'newpr-a6131',
    storageBucket: 'newpr-a6131.appspot.com',
    iosBundleId: 'com.example.studentManagementAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRlPUF_rTorkZTteByKoIBECZEMrDVwTk',
    appId: '1:782550248358:ios:70ff81294ab9b32d443d67',
    messagingSenderId: '782550248358',
    projectId: 'newpr-a6131',
    storageBucket: 'newpr-a6131.appspot.com',
    iosBundleId: 'com.example.studentManagementAppFirebase.RunnerTests',
  );
}
